APP = university
SHELL = /bin/bash
DOCKER_COMPOSE_FILE = docker-compose.yml

.PNONY: help
help: Makefile
	@echo
	@echo "Choose a command run in "$(APP)":"
	@echo
	@fgrep -h "##" $(MAKEFILE_LIST) | sed -e 's/\(\:.*\#\#\)/\:\ /' | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'

build: ## Build app
	go build -o bin/server cmd/main.go

test: ## Test app
	go test -failfast -count=1 -v ./... -coverpkg=./... -coverprofile=coverpkg.
	
migrate-create:
	migrate create -ext sql -dir migrations -seq $(NAME)

migrate-up: 
	migrate -path migrations -database postgres://postgres:postgres@localhost:5434/university?sslmode=disable up

migrate-down: 
	migrate -path migrations -database postgres://postgres:postgres@localhost:5434/university?sslmode=disable down

start: ## Start all deployed services
	docker-compose -f $(DOCKER_COMPOSE_FILE) up -d

stop: ## Stop all deployed services
	docker-compose -f $(DOCKER_COMPOSE_FILE) stop

# redeploy: ## Redeploy go services	
# 	docker-compose -f $(DOCKER_COMPOSE_FILE) stop $(GO_SERVICE); \
# 	docker-compose -f $(DOCKER_COMPOSE_FILE) rm -f $(GO_SERVICE); \
# 	docker-compose -f $(DOCKER_COMPOSE_FILE) up --build -d $(GO_SERVICE); \
# 	docker-compose -f $(DOCKER_COMPOSE_FILE) restart proxy; \